from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.responses import JSONResponse
from app.backend.controllers.user_controller import user_router
from app.backend.controllers.note_controller import note_router
from app.backend.controllers.ai_controller import ai_router
from app.backend.controllers.auth_controller import auth_router
from app.backend.database.database import init_db
from fastapi.middleware.cors import CORSMiddleware
import os
import dotenv

dotenv.load_dotenv()

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")
ALLOWED_ORIGINS = [origin.strip() for origin in FRONTEND_URL.split(",") if origin.strip()]


@asynccontextmanager
async def lifespan(app: FastAPI):
    await init_db()
    yield


app = FastAPI(
    title="AI Knowledge Base API (Local LLM Assistant)",
    version="1.0",
    description=(
        "An API where the user can:\n\n"
        "- **Save content** (notes, articles, ideas)\n"
        "- **Ask questions** about this content\n"
        "- **Receive answers** generated by an LLM (Groq)"
    ),
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health", tags=["health"])
async def health_check():
    return JSONResponse(content={"status": "ok"})


app.include_router(user_router)
app.include_router(note_router)
app.include_router(ai_router)
app.include_router(auth_router)